<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.CleanArchitecture.Template.Contracts</RootNamespace>
        <AssemblyName>Genocs.CleanArchitecture.Template.Contracts</AssemblyName>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

</Project>
