language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 6.0.101
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/build.sh
  - ./scripts/test.sh
after_success:
  #- ./scripts/dotnet-pack.sh
notifications:
  email:
    on_success: never
    on_failure: always
