@url = https://localhost:5001
@apiVersion = api-version=1.0

@customerId = 8c62fa8e-7a32-4851-b2ac-21e9d62a9f2d

### Create a customer
POST {{url}}/api/v1/Customers?{{apiVersion}} HTTP/1.1
Content-Type: application/json

{
  "ssn": "2410196812",
  "name": "Giovanni",
  "initialAmount": 100
}

### Get an existing customer
GET {{url}}/api/v1/Customers/{{customerId}}?{{apiVersion}} HTTP/1.1


