FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY . .
RUN dotnet publish src/Genocs.MicroserviceLight.Template.BusHost -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app/out .
ENV ASPNETCORE_ENVIRONMENT Docker
ENTRYPOINT dotnet Genocs.MicroserviceLight.Template.BusHost.dll
