version: '3.9'

services:
  genocs.cleanarchitecture.template.webapi:
    image: ${DOCKER_REGISTRY-}genocs.cleanarchitecture.template.webapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
