version: '3.4'

services:
  genocs.microservicelight.template.webapi:
    image: ${DOCKER_REGISTRY-}genocsmicroservicelighttemplatewebapi
    build:
      context: .
      dockerfile: src/Genocs.MicroserviceLight.Template.WebApi/Dockerfile
