name: Build Test and Pack

on:
  push:
    branches: [main]
    paths-ignore: ["assets/**", "docs/**", "examples/**"]
  pull_request:
    branches: [main]
    paths-ignore: ["assets/**", "docs/**", "examples/**"]

jobs:
  build:
    name: Build Test and Pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Debug --no-restore

      - name: Test
        run: dotnet test -c Debug --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --results-directory TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: GenocsTestResults
          path: TestResults/*.trx

      - name: Pack
        run: dotnet pack -c Debug --no-build --verbosity normal
