<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Genocs.CleanArchitecture.Template.Domain</RootNamespace>
        <AssemblyName>Genocs.CleanArchitecture.Template.Domain</AssemblyName>
        <IsPublishable>false</IsPublishable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Genocs.Common" Version="9.0.0-beta001" />
    </ItemGroup>

</Project>
